### ISSUE TITLE
دانلود تکالیف

### ISSUE THREAD

**Issue by mjmaher987** [titansarus/QueraToCsv#6]
سلام.
کدی هست که همه پاسخ های تمارین کوئرا رو دانلود کنه؟
مثلا سی دبلیو یه گزینه داره "دریافت تمام تکالیف تحویل داده شده" ولی کوئرا همچین چیزی نداره.

**Comment by titansarus** [comment]
Salaam,
Quera has the ability to download all assignments (grouped by question or user):
<img width="416" alt="image" src="https://user-images.githubusercontent.com/22544859/215002412-f710410b-0ea1-47cb-9242-bbb142e54329.png">
I also think that Quera has some bugs for assignments with a very high number of submissions, but it usually works fine.

@mjmaher987

**Comment by mjmaher987** [comment]
اها نمیدونستم.
خیلی ممنون.
